lastupdatecheck: 0
recentrepos:
- /home/alexp/repos/dotfiles
- /home/alexp/repos/help-students-app
- /home/alexp/repos/cdp
- /home/alexp/repos/help-students-backend
startuppopupversion: 5
customcommandshistory:
- 'fix: remove establishment field from address and contact details forms and add
  validation'
hidecommandlog: false
